sudo: required
services:
  - docker

before_install:
  - docker build -t examgoal/app-status-nodejs -f Dockerfile.dev .

script:
  - docker run examgoal/app-status-nodejs npm run test

deploy:
  - provider: elaticbeanstalk
    region: ap-south-1
    app: "AppStatusNodeJS"
    env: "DOCKER-SC"
    bucket_name: "elasticbeanstalk-ap-south-1-365956621235"
    bucket_path: "AppStatusNodeJS"
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
      secure: "$AWS_SECRET_KEY"
