steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/app-status-royapis-service:${_DOCKER_TAG}', '.']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/app-status-royapis-service:${_DOCKER_TAG}']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', '${_RUN_SERVICE}', '--image', 'gcr.io/$PROJECT_ID/app-status-royapis-service:${_DOCKER_TAG}', '--region', 'asia-south1', '--platform', 'managed', '--allow-unauthenticated']
images:
  - gcr.io/$PROJECT_ID/app-status-royapis-service:${_DOCKER_TAG}
options:
  substitutionOption: MUST_MATCH